# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('github', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/projects/')),
            ],
        ),
    ]
