# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='Language',
            field=models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Javascript', 'JavaScript'), ('Python', 'Python'), ('C++', 'C++')], default='Python', max_length=10),
            preserve_default=False,
        ),
    ]
