# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_auto_20190213_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Language',
            new_name='language',
        ),
    ]
