# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0004_auto_20190218_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('a', 'Java'), ('b', 'JavaScript'), ('c', 'Python'), ('d', 'C++'), ('e', 'PHP'), ('f', 'HTML')], max_length=10),
        ),
    ]
