# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0006_project_isonprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('C++', 'C++'), ('PHP', 'PHP'), ('HTML', 'HTML')], max_length=2),
        ),
    ]
