# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0007_auto_20190218_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('C++', 'C++'), ('PHP', 'PHP'), ('HTML', 'HTML')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='personal_info.Language'),
        ),
    ]
